stages:
  - name: contur
    dependencies: ['init']
    scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
        inputyoda: {output: yoda, step: init}
        output_analysis: "{workdir}/ANALYSIS"
        output_plots: "{workdir}/plots"
      step: {$ref: 'step.yml'}
